### ISSUE TITLE
"Updating is impossible because there's not enough space"

### ISSUE THREAD

**Issue by liquidbear99** [Hypfer/Valetudo#1282] opened 2021-12-15 03:34 UTC
Describe the bug
"Updating is impossible because there's not enough space"

Is there a command I could run from by vacuum to help this.

Attempt to update the robot.

Screenshots
See below

Vacuum Model
Roborock S5

Valetudo Version
2021.12.0

Expected behavior
I should be able to update or clear memory in order to update.

Additional context

![image](https://user-images.githubusercontent.com/53712660/146118265-60af35e6-80ee-45c0-9b8b-f98b3e7a0835.png)
![image](https://user-images.githubusercontent.com/53712660/146119039-55bd2ca2-b41e-47f6-8fce-3e273c1c14f7.png)

**Comment by rimrul** [comment] 2021-12-15 05:43
Not a bug. Also a duplicate of #1234. You likely didn't resize your roottfs.

**Closed** 2021-12-15 08:09 UTC
Labels: bug
