### ISSUE TITLE
Zone cleaning is reapeated multiple times

### ISSUE THREAD

**Issue by JanickGers85** [Hypfer/Valetudo#574] opened 2020-07-30 13:07 UTC
Zone cleaning is reapeated multiple times; 1m^3 cleaned for 10 mins.

## To Reproduce
1. Start a zone cleaning (via web ui or MQTT command)
2. Zone is cleaned multiple time (didn't count, but more than 5 for sure 😄)

### Screenshots
![chrome_2020-07-30_15-02-30](https://user-images.githubusercontent.com/21289907/88926628-89514500-d276-11ea-8071-a5ee47c26b8f.png)

A lot of paths 😄 

### Vacuum Model
Xiaomi Gen1

### Valetudo Version
0.6.0

### Firmware Version
v11_004007jjsfghfdff.fullos.pkg

## Expected behavior
A single clean as for valetudo v0.4.0

**Comment by Hypfer** [comment] 2020-07-30 14:52
Duplicate of #573 and fixed in 0.6.1

**Comment by Hypfer** [comment] 2020-07-30 14:52
10 times btw. I've accidentially multiplied the iterations by 10

**Closed by Hypfer** 2020-07-30 14:52 UTC
Labels: bug
