### ISSUE TITLE
Backslash "\" is not recognized as char but as escape character in Wifi password

### ISSUE THREAD

**Issue by rweishaupt** [Hypfer/Valetudo#596] opened 2020-09-08 17:29 UTC
So, I just tried to update my robot's wifi password and found out that if there occurs a "\\" in the wifi password either the website or something internal treats the \ as an escape character instead of a normal character.

Example:

Wifi password: test\1
Saved password in `/mnt/data/wlan/wpa_supplicant.conf`: test1

In order to fix this, you have to escape the \ character in your password on the website, i.e., enter test\\1 as wifi password.

**Comment by Hypfer** [comment] 2020-09-08 17:32
Duplicate of #419

Please check the issue tracker for existing issues before opening a new one. Thank you

**Closed by Hypfer** 2020-09-08 17:32 UTC
Labels: duplicate
