### ISSUE TITLE
Add forbidden zones

### ISSUE THREAD

**Issue by theFork** [Hypfer/Valetudo#162] opened 2019-04-08 17:16 UTC
In many cases it is useful to prevent the robot to enter certain areas, for instance the pile of clothes next to someones bed ;)
I think there are many more usecases for this.

**Comment by cryptomilk** [comment] 2019-04-08 17:18
This is a duplicate of #132.

@Hypfer maybe change the name of #132 to: Persistant Maps, No-Go Zones and Virtual Barriers

**Closed** 2019-04-08 17:20 UTC
