### ISSUE TITLE
Unsupported velocity value for manual control

### ISSUE THREAD

**Issue by Algram** [Hypfer/Valetudo#1464] opened 2022-04-08 20:32 UTC
## To Reproduce
Start manual control, press forward or backward, nothing happens.

Rotating still works

### Vacuum Model
Xiaomi Vacuum 1

### Valetudo Version
2022.3.1

## Expected behavior
Forward and backwards should work

## Additional context
Through debugging with `python-miio` I have found the actual issue:
A velocity of `0.3` is not supported by this robot. `0.29` still works, but anything over that apparently gets ignored. So the fix would be to adapt the velocity here:

https://github.com/Hypfer/Valetudo/blob/7e9ef04b2fa5d8fb4d5f7e8d3fa88366592873ea/backend/lib/robots/roborock/capabilities/RoborockManualControlCapability.js#L64

**Comment by Hypfer** [comment] 2022-04-10 08:14
Duplicate of #1307 

Thanks for taking your time to debug that though!

**Closed by Hypfer** 2022-04-10 08:14 UTC
Labels: duplicate
