### ISSUE TITLE
Maps not loading on iOS browsers

### ISSUE THREAD

**Issue by talondnb** [Hypfer/Valetudo#312] opened 2019-08-25 11:00 UTC
As per https://github.com/Hypfer/Valetudo/issues/295, I'd like to open this issue. I'm unable to load the Map section under iOS in both Safari and Chrome browsers. I've also tried clearing cache and enabling all experimental features in Safari settings but the map still won't load.

Running iOS 12.4 and latest Valetudo on Gen2 S55.

**Comment by Admonstrator** [comment] 2019-09-07 12:21
I can confirm this issue.

Running iOS 12.4.1 + Valetudo 0.4.0 on FW 3.3.9 (Build 001720)

**Comment by BirokratskaZila** [comment] 2019-09-07 21:34
Same issue for me.

iOS 12.4 + Valentudo 0.4.0 on FW 3.3.9 (Build 003468)

**Comment by nikolaykasyanov** [comment] 2019-10-11 21:33
I'm observing the same behaviour on Safari for macOS as well. Console gives a clue:

```
[Error] Blocked http://rockrobo/zone/js-modules/vacuum-map.js from asking for credentials because it is a cross-origin request.
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (vacuum-map.js, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (icon.png, line 0)
```

**Comment by onkelandy** [comment] 2019-10-17 05:49
I can see the map with latest OS and Valetudo. Have to drag my finger over the whole screen to zoom out. Problem: not possible to pan/move the map and zoom center is wrong

**Comment by onkelandy** [comment] 2019-10-18 05:50
Just tried it with iOS 13 and it seems to work on an iPhone 7 in Safari

**Comment by ottelo9** [comment] 2019-11-05 07:15
I've problems that the map doesnt refresh automatically in chrome for PC. And I've the same problems with iOS not showing the map on iOS12.

**Comment by ottelo9** [comment] 2019-11-13 06:47
Update:
After disable HTTP Login the map is displayed on my iOS devices! So its a problem with http login.

**Comment by talondnb** [comment] 2019-11-13 07:39
I've also tested this, iOS 13.2.2 and I've just disabled http login and it's now showing the map. Thanks @ottelo9

**Comment by LasseSLambertsen** [comment] 2019-11-28 16:27
Same issue here, disabling http auth fixes it.
Though not a solution for me as it is accessible over internet

**Comment by Hypfer** [comment] 2020-05-15 10:44
This won't be fixed unless someone with an Apple devices opens a PR.

**Comment by IzK666** [comment] 2020-05-20 17:47
Today is my first day with valetudo.
I'm having the same issue, but nothing to do with IOS: Just any "lite" browser in android.
I use Lightning browser, but I tested on Opera Lite and Firefox Lite with the same result: The map isn't loading at all. I tried to create a new zone but the map is blank and can't draw anything.

**Comment by Hypfer** [comment] 2020-05-20 18:20
I just tried the Opera Mini Beta on android and got a map rendered.
It was rather slow though.
Same goes for Lightning Browser. That one is quicker though.
> Speed - By utilizing the WebKit rendering engine that comes built into your Android device, Lightning can ensure a swift, lightweight experience.

I'm using Android 9 so the WebView might be newer than yours.

Can't test Firefox lite since it's not avaliable in Germany, sadly :/


Anyways. These are probably unrelated issues.

**Comment by IzK666** [comment] 2020-05-20 21:06
You're right. The issue is my android 7 (WebView 60). After update I can see the map.
Thanks.

**Comment by Hypfer** [comment] 2020-08-06 14:38
252c22d might've fixed this

**Closed** 2021-01-12 08:25 UTC
Labels: bug, help wanted, pr required
