### ISSUE TITLE
[Feature Request] Localizations for client's WebUI

### ISSUE THREAD

**Issue by HackintoshHD** [Hypfer/Valetudo#384] opened 2019-11-30 12:31 UTC
I'd like to propose adding localizations to the client's WebUI so that the user interface can appear in different languages based on your device's locale. I see this has already been implemented in Valetudo RE [here](https://github.com/rand256/valetudo/commit/63d3039da11e7d6719b0a81ce5c341667d0a583d).

**Comment by rimrul** [comment] 2019-11-30 13:48
The Valetudo RE commit could probably be adapted to Valetudo. I would import the packages([i18next](https://github.com/i18next/i18next),[i18next xhr backend](https://github.com/i18next/i18next-xhr-backend),[loc-i18next](https://github.com/mthh/loc-i18next)) via `package.json` or `yarn.lock`. There have also been some changes to Valetudo (and Valetudo RE) since ee509ca, which seems to be the latest Valetudo commit in Valetudo RE.

**Comment by HHenning0815** [comment] 2020-01-05 19:22
I would like to have localisation also (WAF and so) - please let know when and how ist possible.

**Comment by Hypfer** [comment] 2020-05-15 10:40
Duplicate of #70

**Closed by Hypfer** 2020-05-15 10:40 UTC
Labels: enhancement, good first issue
